export const vehicleData = [
  {
    specs: {},
    trims: [
      {
        id: 23156,
        make_model_id: 332,
        year: 2015,
        name: "FE+ S",
        description: "FE+ S 4dr Sedan (1.8L 4cyl CVT)",
        msrp: 17780,
        invoice: 17329,
        make_model_trim_mileage: {
          id: 23156,
          combined_mpg: 34,
          range_city: 3960,
          range_highway: 5280,
          epa_combined_mpg_electric: null,
        },
        make_model_trim_engine: {
          id: 23156,
          engine_type: "gas",
          fuel_type: "regular unleaded",
          drive_type: "front wheel drive",
          transmission: "continuously variable-speed automatic",
        },
        make_model_trim_body: {
          id: 23156,
          type: "Sedan",
          doors: 4,
          seats: 5,
          cargo_capacity: "15.1",
          max_cargo_capacity: null,
          max_payload: null,
          max_towing_capacity: null,
        },
        make_model: {
          id: 332,
          make_id: 19,
          name: "Sentra",
          make: {
            id: 19,
            name: "Nissan",
          },
        },
      },
    ],
  },

  {
    specs: {},
    trims: [
      {
        id: 1,
        make_model_id: 2,
        year: 1998,
        name: "Interceptor",
        description: "SHE DRINKS NITRO",
        msrp: 123456,
        invoice: 12345,
        make_model_trim_mileage: {
          id: 1,
          combined_mpg: 10,
          range_city: 400,
          range_highway: 500,
          epa_combined_mpg_electric: null,
        },
        make_model_trim_engine: {
          id: 1,
          engine_type: "gas",
          fuel_type: "regular unleaded",
          drive_type: "front wheel drive",
          transmission: "STICK SHIFT",
        },
        make_model_trim_body: {
          id: 1,
          type: "Coupe",
          doors: 2,
          seats: 2,
          cargo_capacity: "6",
          max_cargo_capacity: null,
          max_payload: null,
          max_towing_capacity: null,
        },
        make_model: {
          id: 1,
          make_id: 2,
          name: "Falcon",
          make: {
            id: 3,
            name: "Ford",
          },
        },
      },
    ],
  },

  {
    specs: {},
    trims: [
      {
        id: 1,
        make_model_id: 2,
        year: 1998,
        name: "Razor Cola",
        description: "THATS MINE",
        msrp: 123456,
        invoice: 12345,
        make_model_trim_mileage: {
          id: 1,
          combined_mpg: 10,
          range_city: 400,
          range_highway: 500,
          epa_combined_mpg_electric: null,
        },
        make_model_trim_engine: {
          id: 1,
          engine_type: "gas",
          fuel_type: "HIGH OCTANE",
          drive_type: "ALL wheel drive",
          transmission: "STICK SHIFT",
        },
        make_model_trim_body: {
          id: 1,
          type: "Coupe",
          doors: 2,
          seats: 2,
          cargo_capacity: "6",
          max_cargo_capacity: null,
          max_payload: null,
          max_towing_capacity: null,
        },
        make_model: {
          id: 1,
          make_id: 2,
          name: "WARBOY",
          make: {
            id: 3,
            name: "Ford",
          },
        },
      },
    ],
  },

  {
    specs: {},
    trims: [
      {
        id: 1,
        make_model_id: 2,
        year: 3000,
        name: "THE ACCELERATOR",
        description: "It rusts",
        msrp: 66666,
        invoice: 77777,
        make_model_trim_mileage: {
          id: 7,
          combined_mpg: 0,
          range_city: 40,
          range_highway: 50,
          epa_combined_mpg_electric: 7,
        },
        make_model_trim_engine: {
          id: 7,
          engine_type: "EV",
          fuel_type: "POWER OF THE SUN",
          drive_type: "Bad financial decisions",
          transmission: "Ask Elon",
        },
        make_model_trim_body: {
          id: 7,
          type: "Truck",
          doors: 2,
          seats: 2,
          cargo_capacity: "6",
          max_cargo_capacity: 8,
          max_payload: 100,
          max_towing_capacity: 8,
        },
        make_model: {
          id: 1,
          make_id: 2,
          name: "Cybertruck",
          make: {
            id: 3,
            name: "Tesla",
          },
        },
      },
    ],
  },
];
