export const mockData = [
  {
    id: 6800,
    make_model_id: 166,
    year: 2020,
    name: "Custom",
    description: "Custom 4dr Crew Cab 4WD LB (6.6L 8cyl 6A)",
    msrp: 43800,
    invoice: 41347,
    created: "2023-06-29T21:00:00-04:00",
    modified: "2023-06-29T21:00:00-04:00",
    make_model_trim_mileage: {
      id: 6800,
      make_model_trim_id: 6800,
      fuel_tank_capacity: "36.0",
      combined_mpg: null,
      epa_city_mpg: null,
      epa_highway_mpg: null,
      range_city: 0,
      range_highway: 0,
      battery_capacity_electric: null,
      epa_time_to_charge_hr_240v_electric: null,
      epa_kwh_100_mi_electric: null,
      range_electric: null,
      epa_highway_mpg_electric: null,
      epa_city_mpg_electric: null,
      epa_combined_mpg_electric: null,
    },
    make_model_trim_engine: {
      id: 6800,
      make_model_trim_id: 6800,
      engine_type: "gas",
      fuel_type: "regular unleaded",
      cylinders: "V8",
      size: "6.6",
      horsepower_hp: 401,
      horsepower_rpm: 5200,
      torque_ft_lbs: 464,
      torque_rpm: 4000,
      valves: 16,
      valve_timing: "Variable",
      cam_type: "Overhead valves (OHV)",
      drive_type: "four wheel drive",
      transmission: "6-speed shiftable automatic",
    },
    make_model_trim_body: {
      id: 6800,
      make_model_trim_id: 6800,
      type: "Truck (Crew Cab)",
      doors: 4,
      length: "266.0",
      width: "81.9",
      seats: 6,
      height: "79.7",
      wheel_base: "172.0",
      front_track: null,
      rear_track: null,
      ground_clearance: "10.1",
      cargo_capacity: null,
      max_cargo_capacity: null,
      curb_weight: 6950,
      gross_weight: 10850,
      max_payload: 3862,
      max_towing_capacity: 14500,
    },
    make_model: {
      id: 166,
      make_id: 6,
      name: "Silverado 2500HD",
      make: {
        id: 6,
        name: "Chevrolet",
      },
    },
    vin: "1GNEL19X73B130926",
    license_plate: "4Rt909",
    purchase_date: "2024-07-01",
    purchase_price: "34000",
    purchase_mileage: "120",
    notes: "",
    interior_color: {
      id: 24750,
      make_model_trim_id: 6800,
      name: "Jet Black, cloth",
      rgb: "0,0,0",
    },
    exterior_color: {
      id: 66780,
      make_model_trim_id: 6800,
      name: "Black",
      rgb: "0,0,0",
    },
    image: "https://i.ytimg.com/vi/x2ViA3Jd0yg/maxresdefault.jpg",
  },

  {
    id: 16494,
    make_model_id: 216,
    year: 2017,
    name: "Si",
    description: "Si 2dr Coupe (1.5L 4cyl Turbo 6M)",
    msrp: 23900,
    invoice: 22202,
    created: "2023-06-29T21:03:31-04:00",
    modified: "2023-06-29T21:03:31-04:00",
    make_model_trim_mileage: {
      id: 16494,
      make_model_trim_id: 16494,
      fuel_tank_capacity: "12.4",
      combined_mpg: 32,
      epa_city_mpg: 28,
      epa_highway_mpg: 38,
      range_city: 3472,
      range_highway: 4712,
      battery_capacity_electric: null,
      epa_time_to_charge_hr_240v_electric: null,
      epa_kwh_100_mi_electric: null,
      range_electric: null,
      epa_highway_mpg_electric: null,
      epa_city_mpg_electric: null,
      epa_combined_mpg_electric: null,
    },
    make_model_trim_engine: {
      id: 16494,
      make_model_trim_id: 16494,
      engine_type: "gas",
      fuel_type: "premium unleaded (recommended)",
      cylinders: "I4",
      size: "1.5",
      horsepower_hp: 205,
      horsepower_rpm: 5700,
      torque_ft_lbs: 192,
      torque_rpm: 2100,
      valves: 16,
      valve_timing: null,
      cam_type: "Double overhead cam (DOHC)",
      drive_type: "front wheel drive",
      transmission: "6-speed manual",
    },
    make_model_trim_body: {
      id: 16494,
      make_model_trim_id: 16494,
      type: "Coupe",
      doors: 2,
      length: "177.3",
      width: "70.9",
      seats: 5,
      height: "54.7",
      wheel_base: "106.3",
      front_track: null,
      rear_track: null,
      ground_clearance: null,
      cargo_capacity: "11.9",
      max_cargo_capacity: null,
      curb_weight: 2889,
      gross_weight: null,
      max_payload: null,
      max_towing_capacity: null,
    },
    make_model: {
      id: 216,
      make_id: 9,
      name: "Civic",
      make: {
        id: 9,
        name: "Honda",
      },
    },
    vin: "1234asdf1234asdf",
    license_plate: "JUSTVIBN",
    purchase_date: "2024-07-15",
    purchase_price: "25000",
    purchase_mileage: "42000",
    notes: "",
    interior_color: {
      id: 60341,
      make_model_trim_id: 16494,
      name: "Black, cloth",
      rgb: "25,25,25",
    },
    exterior_color: {
      id: 168652,
      make_model_trim_id: 16494,
      name: "White Orchid Pearl",
      rgb: "251,251,240",
    },
    image:
      "https://www.townsendhonda.com/wp-content/plugins/di-honda-integration/assets/img/model-images/2017-civic-sedan/colors/model-color-2017-civic-sedan-white-orchid-pearl.png",
  },

  {
    id: 8894,
    make_model_id: 368,
    year: 2020,
    name: "Launch Edition",
    description: "Launch Edition 2dr Coupe (3.0L 6cyl Turbo 8A)",
    msrp: 55250,
    invoice: 50278,
    created: "2023-06-29T21:00:02-04:00",
    modified: "2023-06-29T21:00:02-04:00",
    make_model_trim_mileage: {
      id: 8894,
      make_model_trim_id: 8894,
      fuel_tank_capacity: "13.7",
      combined_mpg: 26,
      epa_city_mpg: 24,
      epa_highway_mpg: 31,
      range_city: 3288,
      range_highway: 4247,
      battery_capacity_electric: null,
      epa_time_to_charge_hr_240v_electric: null,
      epa_kwh_100_mi_electric: null,
      range_electric: null,
      epa_highway_mpg_electric: null,
      epa_city_mpg_electric: null,
      epa_combined_mpg_electric: null,
    },
    make_model_trim_engine: {
      id: 8894,
      make_model_trim_id: 8894,
      engine_type: "gas",
      fuel_type: "premium unleaded (required)",
      cylinders: "I6",
      size: "3.0",
      horsepower_hp: 335,
      horsepower_rpm: 5000,
      torque_ft_lbs: 365,
      torque_rpm: 1600,
      valves: 24,
      valve_timing: "Variable",
      cam_type: "Double overhead cam (DOHC)",
      drive_type: "rear wheel drive",
      transmission: "8-speed shiftable automatic",
    },
    make_model_trim_body: {
      id: 8894,
      make_model_trim_id: 8894,
      type: "Coupe",
      doors: 2,
      length: "172.5",
      width: "73.0",
      seats: 2,
      height: "50.9",
      wheel_base: "97.2",
      front_track: null,
      rear_track: null,
      ground_clearance: "4.5",
      cargo_capacity: "10.2",
      max_cargo_capacity: "10.2",
      curb_weight: 3397,
      gross_weight: 4001,
      max_payload: 604,
      max_towing_capacity: null,
    },
    make_model: {
      id: 368,
      make_id: 22,
      name: "GR Supra",
      make: {
        id: 22,
        name: "Toyota",
      },
    },
    vin: "f45t4ndfur10u5",
    license_plate: "2Fast4U",
    purchase_date: "2024-07-15",
    purchase_price: "55555",
    purchase_mileage: "0",
    notes: "",
    interior_color: {
      id: 32238,
      make_model_trim_id: 8894,
      name: "Black, leather",
      rgb: "29,29,29",
    },
    exterior_color: {
      id: 89368,
      make_model_trim_id: 8894,
      name: "Absolute Zero",
      rgb: "240,240,240",
    },
    image: "https://i.ytimg.com/vi/qhP5rckjRPA/maxresdefault.jpg",
  },
];
